# Generated by Django 5.1.3 on 2024-11-30 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("office", "0002_member"),
    ]

    operations = [
        migrations.CreateModel(
            name="Group_name",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="", max_length=100)),
                ("address", models.CharField(default="", max_length=1000)),
                ("member_installment", models.FloatField(default=0)),
            ],
        ),
    ]
