# Generated by Django 5.1.3 on 2024-11-30 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("office", "0003_group_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="group_name",
            old_name="member_installment",
            new_name="member_installment_limit",
        ),
    ]
