# Generated by Django 5.1.3 on 2024-11-30 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "office",
            "0004_rename_member_installment_group_name_member_installment_limit",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Member_installment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.FloatField()),
                ("date", models.DateField(auto_now_add=True)),
                ("added_date", models.DateTimeField(auto_now_add=True)),
                (
                    "member",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="office.member",
                    ),
                ),
                (
                    "office_employee",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="office.office_employee",
                    ),
                ),
            ],
        ),
    ]
