# Generated by Django 5.1.3 on 2024-11-30 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("office", "0005_member_installment"),
    ]

    operations = [
        migrations.AddField(
            model_name="group_name",
            name="maximum_loan",
            field=models.FloatField(default=0),
        ),
    ]
