# Generated by Django 5.1.3 on 2024-12-01 03:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("office", "0006_group_name_maximum_loan"),
    ]

    operations = [
        migrations.CreateModel(
            name="Member_loan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("loan_amount", models.FloatField()),
                ("date", models.DateField(auto_now_add=True)),
                ("added_date", models.DateTimeField(auto_now_add=True)),
                ("loan_status", models.IntegerField(default=1)),
                (
                    "member",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="office.member",
                    ),
                ),
                (
                    "office_employee",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="office.office_employee",
                    ),
                ),
            ],
        ),
    ]
