# Generated by Django 5.1.3 on 2024-12-01 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("office", "0007_member_loan"),
    ]

    operations = [
        migrations.AddField(
            model_name="group_name",
            name="loan_interest",
            field=models.FloatField(default=0),
        ),
    ]
