# Generated by Django 5.1.3 on 2024-12-01 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("office", "0009_member_loan_installment_member_loan_interest"),
    ]

    operations = [
        migrations.AddField(
            model_name="member_loan_installment",
            name="Loan",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="office.member_loan",
            ),
        ),
        migrations.AddField(
            model_name="member_loan_interest",
            name="Loan",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="office.member_loan",
            ),
        ),
    ]
