# Generated by Django 5.1.3 on 2024-12-01 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("office", "0010_member_loan_installment_loan_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="member_loan_interest",
            old_name="Loan",
            new_name="loan",
        ),
        migrations.RemoveField(
            model_name="member_loan_installment",
            name="Loan",
        ),
        migrations.AddField(
            model_name="member_loan_installment",
            name="loan",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="office.member_loan",
            ),
        ),
    ]
