# Generated by Django 5.1.3 on 2024-12-01 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("office", "0011_rename_loan_member_loan_interest_loan_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="group_name",
            name="date",
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
