# Generated by Django 5.1.3 on 2024-12-02 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("office", "0012_group_name_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="member_loan_installment",
            name="interest_amount",
            field=models.FloatField(null=True),
        ),
        migrations.DeleteModel(
            name="Member_loan_interest",
        ),
    ]
