# Generated by Django 5.1.3 on 2024-12-03 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("office", "0013_member_loan_installment_interest_amount_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Loan_demand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("demand_amount", models.FloatField(null=True)),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "member",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="office.member",
                    ),
                ),
            ],
        ),
    ]
