# Generated by Django 5.1.3 on 2024-12-04 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("office", "0014_loan_demand"),
    ]

    operations = [
        migrations.AddField(
            model_name="member_loan",
            name="minimum_loan_installment",
            field=models.FloatField(default=0),
        ),
    ]
